# Generated by Django 2.2.4 on 2020-06-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('companyName', models.CharField(max_length=200)),
                ('companyStockCode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('companyBuz', models.TextField()),
                ('companyProd', models.TextField()),
                ('companyListStartDate', models.CharField(max_length=200)),
                ('companyCEO', models.CharField(max_length=200)),
                ('companySite', models.CharField(max_length=200)),
                ('companyLocal', models.CharField(max_length=200)),
            ],
        ),
    ]
